### ISSUE TITLE
The relation with thesyntaxinator/TouchGuard?

### ISSUE THREAD

**Issue by GJRobert** [amanagr/TouchGuard#1]
Hi amanagr,

Thanks for creating this project and spreading it out. I'm now using your script.

I happen to find [thesyntaxinator/TouchGuard: Disable mac touchpad while typing to avoid cursor jumping](https://github.com/thesyntaxinator/TouchGuard "thesyntaxinator/TouchGuard: Disable mac touchpad while typing to avoid cursor jumping") today. May I ask about the difference between your project and it? Are these similar in the bottom layer?

**Comment by amanagr** [comment]
I think I made some changes in the code. Other than that, They are the same.
