### ISSUE TITLE
Doesn't work on catalina

### ISSUE THREAD

**Issue by thesyntaxinator** [amanagr/TouchGuard#4]
Says operation not permitted when I try to copy the executable to /usr/bin, even with sudo

**Comment by amanagr** [comment]
Sorry, I haven't used it for a while. If you know a fix, open a PR. I will be more than happy to review and merge it.

**Comment by thesyntaxinator** [comment]
Thanks, will do if I think of a fix.

**Comment by swealpha** [comment]
Is it not possible to choose another folder than usr/bin?

**Comment by thesyntaxinator** [comment]
#5 should resolve this; feel free to merge and then close this issue if it looks good to you
